using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Syscon_Solution.LSprogram.Setting
{
    public partial class roboteditForm : Form
    {
        public roboteditForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
        }
        string strrobotid;
        string strrobotname;
        string strrobotip;
        string strrobotgroup;
        int actionIDX;

        public void onDBRead_Robotlist()
        {
            string sql = "";
            bool bdataok = false;

            try
            {
                sql = string.Format("SELECT * FROM robot_t ");

                DataSet ds = new DataSet();
                MySqlDataAdapter da = new MySqlDataAdapter(sql, Data.Instance.G_DynaSqlCon);
                da.Fill(ds);

                int ncnt = ds.Tables[0].Rows.Count;
                if (ncnt > 0)
                {
                    for (int i = 0; i < ncnt; i++)
                    {
                        strrobotid = ds.Tables[0].Rows[i]["robot_id"].ToString();
                        strrobotname = ds.Tables[0].Rows[i]["robot_name"].ToString();
                        strrobotip = ds.Tables[0].Rows[i]["address"].ToString();
                        strrobotgroup = ds.Tables[0].Rows[i]["robot_group_id"].ToString();
                    }
                }
            }
            catch (MySqlException ex)
            {
                Console.Out.WriteLine("onDBRead_Robotlist err :={0}", ex.Message.ToString());
            }
            catch (Exception ex2)
            {
                Console.Out.WriteLine("onDBRead_Robotlist err :={0}", ex2.Message.ToString());
            }
        }

        private void gridView1_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            strrobotname = gridView1.GetFocusedRowCellValue("task_name").ToString();
            strrobotid = gridView1.GetFocusedRowCellValue("task_id").ToString();
            strrobotip = gridView1.GetFocusedRowCellValue("mission_list").ToString();
            strrobotgroup = gridView1.GetFocusedRowCellValue("robot_list").ToString();
            actionIDX = gridView1.GetDataSourceRowIndex(e.RowHandle);
        }
    }
    
}
