using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Syscon_Solution.LSprogram
{
    public partial class taskEdit : Form
    {

        LSprogram.mainForm mainform;
        public taskEdit()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            DateTime dt = DateTime.Now;
            string strtime = string.Format("{0:d4}{1:d2}{2:d2}{3:d2}{4:d2}", dt.Year, dt.Month, dt.Day, dt.Hour, dt.Minute);//DateTime.Now.ToString("yyyyMMddHH");
            string strjobid = "Task_" + strtime;

            panel1.Enabled = true;



            taskidTextbox.Text = strjobid;

        }
        private void onMissionlistRead()
        {
            try
            {
                mainform.dbBridge.onDBRead_Missionlist();
                int ncnt = Data.Instance.missionlisttable.missioninfo.Count;


                for (int i = 0; i < ncnt; i++)
                {

                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("TaskEdit_Ctrl ..onMissionlistRead err" + ex.Message.ToString());
            }
        }

        private void button2_Click(object sender, EventArgs e)
        {
            taskidTextbox.Text = "-";
            tasknameTextbox.Text = "-";
            taskstatusTextbox.Text = "NONE";

            panel1.Enabled = true;
        }

        private void saveButton_Click(object sender, EventArgs e)
        {
            string taskid = taskidTextbox.Text;
            string taskname = tasknameTextbox.Text;
            string taskstatus = taskstatusTextbox.Text;
        }
    }
}
